site_name: start-django Docs
site_description: Django + fly.io, styled by Tailwind, htmx-ed
site_url: https://mv3.dev
site_author: Marcelino Veloso III
repo_url: https://github.com/justmars/start-django
docs_dir: "../docs"
dev_addr: "127.0.0.1:8001"
theme:
  name: "material"
  features:
    - content.tabs.link
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - Setup:
    - Post-Installation: setup/summary.md
    - Use Postgres: setup/use-postgres.md
    - User Model:
      - Concept: setup/user-model.md
      - Email Auth: setup/auth-email.md
      - Social Auth:
        - Setup: setup/auth-social.md
        - Github: setup/auth-github.md
        - Google: setup/auth-google.md
        - Facebook: setup/auth-fb.md
    - Cloudflare Images: setup/cloudflare-images.md
    - Postmark Email: setup/email-postmark.md
    - Background Tasks: setup/background-tasks.md
  - Contexts:
    - Overview: contexts/overview.md
    - Local: contexts/local.md
    - IDE: contexts/ide.md
    - REPL: contexts/repl.md
    - Repo: contexts/repo.md
    - Container: contexts/container.md
    - Site: contexts/site.md
  - Design: design.md
  - Deploy:
    - Fly.io:
      - Prep: deploy/prep.md
      - Deploy: deploy/deploy.md
      - Config: deploy/config.md
    - Digital ocean: deploy/do.md
  - Reference:
    - Personalization: references/personalization.md
    - Settings: references/settings.md
    - Conventions: references/conventions.md
    - Env Variables: references/env-vars.md
    - Tailwind Setup: references/tailwind-setup.md
    - Gotchas: references/gotchas.md
  - Misc:
    - Why: extra/why.md
    - Request-Response: extra/request-response.md
    - Production Server: extra/production-server.md
    - Reactive HTMX: extra/reactive-htmx.md
extra:
  homepage: https://mv3.dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/justmars
      name: justmars on Github
    - icon: fontawesome/brands/mastodon
      link: https://esq.social/@mv
      name: mv on Mastodon
copyright: Copyright &copy; Marcelino Veloso III
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_category_heading: true
            show_source: true
            heading_level: 3
  - search:
      lang: en
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
