# Generated by Django 4.2.1 on 2023-05-10 10:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["category", "version"],
                    ),
                ),
                ("text", models.TextField()),
                (
                    "version",
                    models.CharField(
                        help_text="Use dashed notation, e.g. 2-1 to mean version 2.1",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                        ],
                        default="terms",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "db_table": "agreements",
                "get_latest_by": ["-version", "-modified"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("signup", "Account Signup"),
                            ("social", "Social Signup"),
                            ("prompt", "Logged-In Prompt"),
                            ("banner", "Banner Pop-Up"),
                        ],
                        default="signup",
                        max_length=7,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.agreement",
                    ),
                ),
            ],
            options={
                "db_table": "user_consents",
            },
        ),
    ]
